### ISSUE TITLE
How do I start a hotspot when there is no Internet?

### ISSUE THREAD

**Issue by 10D24D** [efebilici/hotspot-controller#2]
hello I think windows can also turn on the mobile hotspot when it is not connected to the Internet, so that the device can use the LAN. Can you solve this problem?

**Comment by efebilici** [comment]
Hello,

Yes, you can create a Hotspot connection on your Windows computer using the Hotspot Controller program even without an internet connection. If you follow the installation instructions correctly, you should be able to establish a Hotspot connection.

Installation instructions: https://github.com/efebilici/hotspot-controller#installation

You can start and stop the hotspot network by clicking the "Start/Stop Hotspot" button through the Hotspot Controller program.
If you encounter any errors despite following these instructions, please feel free to ask for assistance.

**Comment by efebilici** [comment]
> hello I think windows can also turn on the mobile hotspot when it is not connected to the Internet, so that the device can use the LAN. Can you solve this problem?

Hello,

Yes, you can create a Hotspot connection on your Windows computer using the Hotspot Controller program even without an internet connection. If you follow the installation instructions correctly, you should be able to establish a Hotspot connection.

Installation instructions: https://github.com/efebilici/hotspot-controller#installation

You can start and stop the hotspot network by clicking the "Start/Stop Hotspot" button through the Hotspot Controller program.
If you encounter any errors despite following these instructions, please feel free to ask for assistance.

**Comment by 10D24D** [comment]
My wireless card doesn't support hosting networks, so I couldn't launch a mobile hotspot. And when I was using this software, I couldn't set the SSID and password

**Comment by efebilici** [comment]
If your hardware does not support Hosted Networks, you cannot create a Wireless Hotspot through this program.

After running CMD as an administrator, enter the command `netsh wlan show drivers`.
If the output contains `Hosted network supported: Yes`, it means your hardware supports Hosted Networks. If the output contains `Hosted network supported: No`, it means your hardware does not support Hosted Networks.

For the Hotspot Controller to function properly, your hardware must support Hosted Networks.

Here are some links that may help you solve your problem:

[How to Create a WiFi Hotspot Using the Command Prompt](https://www.wikihow.com/Create-a-WiFi-Hotspot-Using-the-Command-Prompt)
[Fixing No Hosted Network](https://www.wikihow.com/Create-a-WiFi-Hotspot-Using-the-Command-Prompt#Fixing-No-Hosted-Network)
[How to Create a Hotspot in Windows 10](https://www.wikihow.com/Create-a-Hotspot-in-Windows-10)
[How to Create a Hotspot in Windows 11](https://www.wikihow.com/Create-a-Hotspot-in-Windows-11)
